site_name: JevOps
docs_dir: docs
site_dir: site

nav:
  - Home: README.md
  - Foundations:
      - Overview: foundations/README.md
      - Linux: foundations/linux.md
      - Networking: foundations/networking.md
      - Git: foundations/git.md
  - Projects:
      - Overview: projects/README.md
      - App:
          - Project: projects/app/README.md
          - CI: projects/app/ci.md
